title: "t0asts' blog"
#description: "I post here sometimes."

baseurl: ""
url: "" 
github_username:  t0asts
author: t0asts

#theme: "minima"
markdown: kramdown
remote_theme: jekyll/minima 
minima:
  skin: dark
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/t0asts"
    
plugins:
  - jekyll-feed
  - jekyll-redirect-from
